### ISSUE TITLE
Plugin crash on buildkite_pipeline data source for a slug that doesn't exist

### ISSUE THREAD

**Issue by PedroArvela** [buildkite/terraform-provider-buildkite#466]
**Describe the bug**

When querying a `buildkite_pipeline` data source with a pipeline slug that doesn't exist, the plugin crashes during planning stage.

**To Reproduce**

Create a terraform project with the following code (assuming valid credentials configured for the provider):

```hcl
data "buildkite_pipeline" "pipeline" {
  slug = "pipeline-slug-that-doesnt-exist"
}
```

Run `terraform plan`, when it runs, the plugin fails with a crash:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-buildkite_v1.3.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x869447]

goroutine 81 [running]:
github.com/buildkite/terraform-provider-buildkite/buildkite.(*pipelineDatasource).Read(0xc00012a048, {0xe32ee8, 0xc0002ceba0}, {{{{0xe377e8, 0xc0002cf380}, {0xbd1920, 0xc0002cf320}}, {0xe392a8, 0xc0002cd640}}, {{{0x0, ...}, ...}, ...}}, ...)
	github.com/buildkite/terraform-provider-buildkite/buildkite/data_source_pipeline.go:109 +0x4a7
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc000181340, {0xe32ee8, 0xc0002ceba0}, 0xc0002cec30, 0xc0003d3638)
	github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_readdatasource.go:79 +0x433
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc000181340, {0xe32ee8?, 0xc0002ce6c0?}, 0xc000112100)
	github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/proto6server/server_readdatasource.go:55 +0x41c
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc000240b40, {0xe32ee8?, 0xc0000bad50?}, 0xc00050a0f0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:659 +0x3df
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0xcc4040?, 0xc000240b40}, {0xe32ee8, 0xc0000bad50}, 0xc0003a20e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:458 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002341e0, {0xe37fe8, 0xc0001029c0}, 0xc000192000, 0xc00036e7e0, 0x13cd1f0, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002341e0, {0xe37fe8, 0xc0001029c0}, 0xc000192000, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 23
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-buildkite_v1.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**

Something like what the `aws_s3_bucket` data source does, which reports that no resource was found:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: reading S3 Bucket (this-bucket-does-not-exist-asdf-bjgersjbgreoi): couldn't find resource
│ 
│   with data.aws_s3_bucket.selected,
│   on test.tf line 18, in data "aws_s3_bucket" "selected":
│   18: data "aws_s3_bucket" "selected" {
│ 
╵```

**Additional context**

This might be reflected in other data sources as well, but this is the one where I caught it, running provider 1.3.0 and terraform 1.6.4

**Comment by jradtilbrook** [comment]
Thanks for raising this, we'll look into it in the next fortnight 👍

**Comment by james2791** [comment]
Hey @PedroArvela 👋

As above - thanks for liaising this; from the above PR - was a relatively straightforward adjustment. If you provide the pipeline datasource with a pipeline slug that doesn't exist, you'll now get an error in the line of `"Could not find pipeline with slug "<org slug>/<pipeline-slug>"` in Terraforms' error diagnostics.

Adjustment will shift into the next release!
